name: Build KSU Riva A10
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Install Alat
      run: sudo apt-get update && sudo apt-get install -y build-essential bc zip curl git-core gcc-aarch64-linux-gnu gcc-arm-linux-gnueabi libssl-dev
    - name: Clone Kernel
      run: git clone --depth=1 -b lineage-17.1 https://github.com/Riva-Development/android_kernel_xiaomi_msm8917.git kernel_workspace
    - name: Pasang KSU
      run: |
        cd kernel_workspace
        curl -LSs "https://raw.githubusercontent.com/rifsxd/KernelSU-Next/next/kernel/setup.sh" | bash -s next
        echo -e "\nint path_umount(struct path *path, int flags)\n{\n\treturn do_umount(path->mnt, flags);\n}\n" >> fs/namespace.c
        sed -i '/#endif \/\* _LINUX_FS_H \*\//i extern int path_umount(struct path *path, int flags);' include/linux/fs.h
        sed -i '/endmenu/i source "drivers/kernelsu/Kconfig"' drivers/Kconfig
        echo "obj-\$(CONFIG_KSU) += kernelsu/" >> drivers/Makefile
        echo "CONFIG_KSU=y" >> arch/arm64/configs/riva_defconfig
        echo "CONFIG_KSU_TAMPERSYS=y" >> arch/arm64/configs/riva_defconfig
        echo "CONFIG_OVERLAY_FS=y" >> arch/arm64/configs/riva_defconfig
        sed -i 's/CONFIG_KPROBES=y/# CONFIG_KPROBES is not set/g' arch/arm64/configs/riva_defconfig
        find drivers/kernelsu -type f -name "*.c" -exec sed -i 's/access_ok(\([^,]*\), \([^)]*\))/access_ok(VERIFY_READ, \1, \2)/g' {} +
    - name: Compile
      run: |
        cd kernel_workspace
        export ARCH=arm64
        export CROSS_COMPILE=aarch64-linux-gnu-
        export CROSS_COMPILE_ARM32=arm-linux-gnueabi-
        make O=out riva_defconfig
        make O=out -j$(nproc --all)
    - name: Bikin ZIP AnyKernel
      run: |
        git clone https://github.com/osm0sis/AnyKernel3.git AnyKernel3
        cd AnyKernel3
        sed -i 's/device.name1=maguro/device.name1=riva/g' anykernel.sh
        cp ../kernel_workspace/out/arch/arm64/boot/Image.gz-dtb . || true
        zip -r9 ../KSU-Riva-Zip.zip *
    - name: Upload ZIP
      uses: actions/upload-artifact@v4
      with:
        name: File-Flash-KSU
        path: KSU-Riva-Zip.zip
